version: '3.8'

services:
  frontend:
    image: docker.io/${DOCKERHUB_USERNAME}/vacation-frontend:v3
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  
networks:
  app-network:
    driver: bridge
