

name: Frontend CICD

on:
  push:
    branches: [ "terraform-cicd" ]
    paths:
      - 'frontend/**'
      - 'terraform/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "terraform-cicd" ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  TF_WORKING_DIR: terraform
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/dream-frontend
  APP_PORT: "3000"

jobs:
  # ============================================================
  # 1. Build and Push Docker Image
  # ============================================================
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Dream-Vacation-App/Dream-Vacation-App/frontend
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  # ============================================================
  # 2. Provision AWS Infrastructure with Terraform
  # ============================================================
  terraform:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    outputs:
      public_ip: ${{ steps.tfout.outputs.public_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform before running any Terraform commands
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5 # Use a stable version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #This command make use of the existing ssh key in EC2
      - name: Set up ssh key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > dream-key.pem
          chmod 600 dream-key.pem

      # Thisgenerate new ssh key in EC2
      # - name: Generate SSH key (if absent)
      #   id: sshkey
      #   run: |
      #     mkdir -p $HOME/.ssh
      #     if [ ! -f "$HOME/.ssh/dream-key" ]; then
      #       ssh-keygen -t ed25519 -N "" -f $HOME/.ssh/dream-key
      #     fi
      #     echo "PUB_KEY=$(cat $HOME/.ssh/dream-key.pub)" >> $GITHUB_OUTPUT

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        env:
          TF_VAR_ssh_public_key: ${{ steps.sshkey.outputs.PUB_KEY }}
        run: terraform plan -out=tfplan

      - name: Terraform apply
        env:
          TF_VAR_ssh_public_key: ${{ steps.sshkey.outputs.PUB_KEY }}
        run: terraform apply -auto-approve tfplan

      - name: Capture Terraform outputs
        id: tfout
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip | head -n 1 | tr -d '\r')
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Save private key for next job
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dream-key
          path: ~/.ssh/dream-key
          retention-days: 3

  # ============================================================
  # 3. Deploy Application to EC2
  # ============================================================
  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download private key
        uses: actions/download-artifact@v4
        with:
          name: dream-key
          path: .
          
      # To verify that the key is downloaded
      - run: ls -la

      - name: Fix key permissions
        run: chmod 600 ./dream-key

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.terraform.outputs.public_ip }}
          username: ${{ secrets.EC2_USER }}
          key: ./dream-key.pem
          source: |
            Dream-Vacation-App/Dream-Vacation-App/docker-compose.yml
          target: /home/ubuntu/

      - name: Deploy app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.terraform.outputs.public_ip }}
          username: ${{ secrets.EC2_USER }}
          key: ./dream-key.pem
          script: |
            set -eux
            sudo apt update -y
            sudo apt install -y docker.io docker-compose-plugin
            sudo systemctl enable --now docker
            
            # Docker login
            echo ${{ secrets.DOCKERHUB_TOKEN }} | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            cd /home/ubuntu
            export DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}
            sudo docker compose -f docker-compose.yml pull
            sudo docker compose -f docker-compose.yml up -d






  # deploy-ec2:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to EC2 via SSH
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.EC2_SSH_KEY }}
  #         script: |
  #           docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v3
  #           docker stop frontend || true
  #           docker rm frontend || true
  #           docker run -d --name frontend -p 3000:80 ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v3
