name: Frontend CICD

on:
  push:
    branches: [ "vacation-cicd" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "vacation-cicd" ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: vacation-frontend

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./Dream-Vacation-App/Dream-Vacation-App/frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    
    deploy-ec2:
      needs: build-and-push
      runs-on: ubuntu-latest

      steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
              docker stop frontend || true
              docker rm frontend || true
              docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest  
      
